# changing_inputs

This Notebook loads an input file, changes the inputs and for each change runs the sap2012 model.

## Setup

In [30]:
%matplotlib inline
import sap2012
import pandas as pd
import matplotlib.pyplot as plt
import random
import numpy as np
s=sap2012.Sap2012()

## Read input file

In [31]:
fp='input_csv_file_high_ins.csv'
s.read_input_csv(fp)

Here this is changed to the three possible options below:

In [32]:
s.inputs['window_u_value']

1.8

# list inputs to adjust values


In [33]:
index_name = ['area', 'average_storey_height','number_of_chimneys_main_heating','number_of_chimneys_secondary_heating','number_of_chimneys_other','number_of_open_flues_main_heating'
             ,'number_of_open_flues_secondary_heating','number_of_open_flues_other','number_of_intermittant_fans_total','number_of_passive_vents_total'
             ,'number_of_flueless_gas_fires_total','air_permeability_value_q50','number_of_storeys_in_the_dwelling'
             ,'structural_infiltration','suspended_wooden_ground_floor_infiltration','no_draft_lobby_infiltration','percentage_of_windows_and_doors_draught_proofed'
             ,'number_of_sides_on_which_dwelling_is_sheltered','monthly_average_wind_speed','mechanical_ventilation_air_change_rate_through_system'
             ,'exhaust_air_heat_pump_using_Appendix_N','mechanical_ventilation_throughput_factor','efficiency_allowing_for_in_use_factor'
             ,'solid_door_net_area','solid_door_u_value','semi_glazed_door_net_area','semi_glazed_door_u_value','window_net_area','window_u_value'
             ,'roof_window_net_area','roof_window_u_value','basement_floor_net_area','basement_floor_u_value','basement_floor_heat_capacity'
             ,'ground_floor_net_area','ground_floor_u_value','ground_floor_heat_capacity','exposed_floor_net_area','exposed_floor_u_value'
             ,'exposed_floor_heat_capacity','basement_wall_gross_area','basement_wall_opening','basement_wall_u_value','basement_wall_heat_capacity'
             ,'external_wall_gross_area','external_wall_opening','external_wall_u_value','external_wall_heat_capacity','roof_gross_area'
             ,'roof_opening','roof_u_value','roof_heat_capacity','party_wall_net_area','party_wall_u_value','party_wall_heat_capacity'
             ,'party_floor_net_area','party_floor_heat_capacity','party_ceiling_net_area','party_ceiling_heat_capacity','internal_wall_net_area'
             ,'internal_wall_heat_capacity','internal_floor_net_area','internal_floor_heat_capacity','internal_ceiling_net_area','internal_ceiling_heat_capacity'
             ,'thermal_bridges_appendix_k','assumed_occupancy','V_dm_table_1c','T_table_1d','water_storage_loss_manufacturer','temperature_factor_table_2b'
             ,'storage_volume_litres','hot_water_storage_loss_table_2','volume_factor_table_2a','Vs_appendix_G3','primary_circuit_loss_table_3'
             ,'combi_loss_table_3','solar_DHW_input_appendix_G','number_of_low_energy_light_bulbs','total_number_of_light_bulbs','frame_factor','window_area'
             ,'light_access_factor_table_6d','light_transmittance_factor_table_6d','pumps_and_fans_gains','solar_radiation_horizontal_plane_monthly_table_U3'
             ,'solar_declination_monthly_table_U3','location_latitude_table_U4','p_tilt','access_factor_table_6d_north','access_factor_table_6d_north_east'
             ,'access_factor_table_6d_east','access_factor_table_6d_south_east','access_factor_table_6d_south','access_factor_table_6d_south_west','access_factor_table_6d_west'
             ,'access_factor_table_6d_north_west','access_factor_table_6d_roof_windows','area_north','area_north_east','area_east','area_south_east','area_south'
             ,'area_south_west','area_west','area_north_west','area_roof_windows','g_table_6b_north','g_table_6b_north_east','g_table_6b_east','g_table_6b_south_east'
             ,'g_table_6b_south','g_table_6b_south_west','g_table_6b_west','g_table_6b_north_west','g_table_6b_roof_windows','FF_table_6b_north','FF_table_6b_north_east','FF_table_6b_east','FF_table_6b_south_east'
             ,'FF_table_6b_south','FF_table_6b_south_west','FF_table_6b_west','FF_table_6b_north_west','FF_table_6b_roof_windows','temperature_during_heating_living_room'
             ,'monthly_external_temperature_table_U1','hours_heating_is_off_1_weekday_living_room','hours_heating_is_off_2_weekday_living_room'
             ,'hours_heating_is_off_1_weekend_living_room','hours_heating_is_off_2_weekend_living_room','hours_heating_is_off_1_weekday_rest_of_dwelling','hours_heating_is_off_2_weekday_rest_of_dwelling'
             ,'hours_heating_is_off_1_weekend_rest_of_dwelling','hours_heating_is_off_2_weekend_rest_of_dwelling','responsiveness_of_heating_system'
             ,'living_room_area','temperature_adjustment_table_4e','efficiency_of_main_space_heating_system_1','efficiency_of_main_space_heating_system_2','efficiency_of_secondary_space_heating_system'
             ,'efficiency_of_water_heater','efficiency_of_water_heater_adjustment_table_4c']

In [34]:
sample = random.sample(index_name,len(index_name))
#sample

# Generate list of input values for each variable

In [35]:
values = []
for i in range(len(sample)):
    values.append(s.inputs[sample[i]])
values
    


[0.76,
 0.0,
 0.0,
 [0, 2.3, 2.3],
 0.0,
 0.68,
 1.0,
 0.0,
 [26, 54, 96, 150, 192, 200, 189, 157, 115, 66, 33, 21],
 0.0,
 0.0,
 0.7,
 10.0,
 0.0,
 0.68,
 0.0,
 0.0,
 0.0,
 0.0,
 0.7,
 0.25,
 0.7,
 4.91,
 [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
 0.77,
 0.0,
 0.0,
 8.0,
 8.99,
 32.027,
 0.7,
 0.7,
 100.0,
 0.0,
 [0, 49.95, 48.99],
 0.0,
 0.68,
 8.0,
 0.0,
 0.0,
 0.0,
 0.0,
 49.95,
 1.21,
 0.7,
 0.0,
 0.0,
 0.77,
 0.11,
 49.95,
 0.0,
 0.0,
 0.0,
 0.7,
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 0.0,
 0.68,
 0.0,
 [41.2, 41.4, 40.1, 37.6, 36.4, 33.9, 30.4, 33.4, 33.5, 36.3, 39.4, 39.9],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 8.0,
 7.0,
 0.68,
 9.0,
 9.0,
 [1.1, 1.06, 1.02, 0.98, 0.94, 0.9, 0.9, 0.94, 0.98, 1.02, 1.06, 1.1],
 26.03,
 0.0,
 8.0,
 0.0,
 0.7,
 113.64,
 0.0,
 0.0,
 0.14,
 1.4,
 84.0,
 9.0,
 [4.3, 4.9, 6.5, 8.9, 11.7, 14.6, 16.6, 16.4, 14.1, 10.6, 7.1, 4.2],
 190.0,
 15.11,
 0.0,
 0.0,
 2.73,
 [-20.7, -12.8, -1.8, 9.8, 18.8, 23.1, 21.2, 13.7, 2.9, -8.7, -18.4, -23.0],
 0.0,
 0.0,
 

In [36]:
runs = ['run_1', 'run_2']

# Rearrange values to 

In [37]:
morris_inputs = dict(zip(sample,random_inputs))
morris_inputs

{'ground_floor_u_value': [[4.3,
   4.9,
   6.5,
   8.9,
   11.7,
   14.6,
   16.6,
   16.4,
   14.1,
   10.6,
   7.1,
   4.2],
  array([ 4.257,  4.851,  6.435,  8.811, 11.583, 14.454, 16.434, 16.236,
         13.959, 10.494,  7.029,  4.158])],
 'party_floor_net_area': [0.0, 0.0],
 'roof_window_u_value': [8.99, 9.0799],
 'average_storey_height': [0.0, 0.0],
 'number_of_chimneys_main_heating': [[41.2,
   41.4,
   40.1,
   37.6,
   36.4,
   33.9,
   30.4,
   33.4,
   33.5,
   36.3,
   39.4,
   39.9],
  array([40.788, 40.986, 39.699, 37.224, 36.036, 33.561, 30.096, 33.066,
         33.165, 35.937, 39.006, 39.501])],
 'g_table_6b_east': [0.7, 0.707],
 'responsiveness_of_heating_system': [0.0, 0.0],
 'hot_water_storage_loss_table_2': [0.0, 0.0],
 'solar_radiation_horizontal_plane_monthly_table_U3': [0.76,
  0.7676000000000001],
 'Vs_appendix_G3': [[0, 2.3, 2.3], array([0.   , 2.323, 2.323])],
 'number_of_passive_vents_total': [0.0, 0.0],
 'FF_table_6b_west': [0.0, 0.0],
 'total_number_of_lig

For each variable, the SAP model is run and the results stored in the `outputs` dictionary:

In [38]:
outputs={} 
EE = {}
EE_table={}
total_energy_used_table = {}
for k in range(4):
    values = []
    value_min = []
    value_max = []
    random_inputs = []
    sample = random.sample(index_name,len(index_name)) #create a trajectory for inputs on each run of the model
    for j in range(len(sample)):
        values.append(s.inputs[sample[j]])
        if (type(values[j])==list):
            calc_list_min = np.array(values[j])
            value_min.append(calc_list_min - 0.01 * calc_list_min)
            calc_list_max = np.array(values[j])
            value_max.append(calc_list_max + 0.01 * calc_list_max)
        else:
            value_min.append(values[j] - 0.01 * values[j])
            value_max.append(values[j] + 0.01 * values[j]) # Create the input values for each input 
        random_inputs.append([values[j],random.choice([value_min[j],value_max[j]])]) #select an value for each input for the model run
        morris_inputs = dict(zip(sample,random_inputs)) #save the input values in a dictionary for the model run
        for i,a in enumerate(morris_inputs[sample[j]]):
            print(sample[j])
            s.inputs[sample[j]] = a
            print(s.inputs[sample[j]])
            s.run()
            outputs[runs[i]]=s.outputs.copy()# needs copy otherwise the same object is placed in all dictionary items
            print(s.outputs['total_energy_used'])
        total_energy_used=[v['total_energy_used'] for v in outputs.values()]
        total_energy_used_table[sample[j]]=(total_energy_used)
        output_table = pd.DataFrame(outputs)
        EE[str (sample[j])] = (output_table.run_2['total_energy_used'] - output_table.run_1['total_energy_used'])/0.01
        EE_table[k]=EE
    s.read_input_csv(fp) #reset the values back to base case, to proceed to next run
        
        
        

energy = pd.DataFrame(total_energy_used_table, index = runs) 
SI = pd.DataFrame(EE_table)    

party_wall_net_area
0.0
11568.759551991416
party_wall_net_area
0.0
11568.759551991416
location_latitude_table_U4
53.5
11568.759551991416
location_latitude_table_U4
54.035
11558.99272055191
g_table_6b_east
0.68
11558.99272055191
g_table_6b_east
0.6868000000000001
11558.99272055191
air_permeability_value_q50
0.0
11558.99272055191
air_permeability_value_q50
0.0
11558.99272055191
basement_wall_gross_area
0.0
11558.99272055191
basement_wall_gross_area
0.0
11558.99272055191
g_table_6b_south
0.68
11558.99272055191
g_table_6b_south
0.6732
11565.259174627632
access_factor_table_6d_south
0.77
11565.259174627632
access_factor_table_6d_south
0.7777000000000001
11559.055363420768
area_roof_windows
0.0
11559.055363420768
area_roof_windows
0.0
11559.055363420768
FF_table_6b_south
0.7
11559.055363420768
FF_table_6b_south
0.693
11565.321234405283
exposed_floor_net_area
0.0
11565.321234405283
exposed_floor_net_area
0.0
11565.321234405283
g_table_6b_south_east
0.68
11565.321234405283
g_table_6b_south_eas

number_of_chimneys_main_heating
0.0
11618.203612538086
number_of_chimneys_main_heating
0.0
11618.203612538086
window_u_value
1.8
11618.203612538086
window_u_value
1.782
11601.771487075139
light_access_factor_table_6d
0.83
11601.771487075139
light_access_factor_table_6d
0.8382999999999999
11601.46393936277
hours_heating_is_off_1_weekend_living_room
0.0
11601.46393936277
hours_heating_is_off_1_weekend_living_room
0.0
11601.46393936277
frame_factor
0.7
11601.46393936277
frame_factor
0.693
11601.774607415018
party_wall_u_value
0.0
11601.774607415018
party_wall_u_value
0.0
11601.774607415018
Vs_appendix_G3
0.0
11601.774607415018
Vs_appendix_G3
0.0
11601.774607415018
FF_table_6b_north
0.7
11601.774607415018
FF_table_6b_north
0.693
11605.915356782427
efficiency_of_secondary_space_heating_system
0.0
11605.915356782427
efficiency_of_secondary_space_heating_system
0.0
11605.915356782427
efficiency_of_main_space_heating_system_2
0.0
11605.915356782427
efficiency_of_main_space_heating_system_2
0.0

ground_floor_net_area
49.95
11774.167830315202
ground_floor_net_area
50.4495
11798.750967728602
number_of_chimneys_main_heating
0.0
11798.750967728602
number_of_chimneys_main_heating
0.0
11798.750967728602
hours_heating_is_off_1_weekend_living_room
0.0
11798.750967728602
hours_heating_is_off_1_weekend_living_room
0.0
11798.750967728602
roof_opening
0.0
11798.750967728602
roof_opening
0.0
11798.750967728602
access_factor_table_6d_north
0.77
11798.750967728602
access_factor_table_6d_north
0.7777000000000001
11794.503753070925
g_table_6b_north_east
0.68
11794.503753070925
g_table_6b_north_east
0.6868000000000001
11794.503753070925
FF_table_6b_north_west
0.7
11794.503753070925
FF_table_6b_north_west
0.693
11794.503753070925
FF_table_6b_north
0.7
11794.503753070925
FF_table_6b_north
0.693
11798.793457728874
window_area
15.11
11798.793457728874
window_area
15.261099999999999
11798.493225800881
area
[0, 49.95, 48.99]
11798.493225800881
area
[ 0.     50.4495 49.4799]
11826.751795851227
living_

11560.299010460369
area_north_west
0.0
11560.299010460369
FF_table_6b_south
0.7
11560.299010460369
FF_table_6b_south
0.693
11566.471463413052
solid_door_net_area
10.92
11566.471463413052
solid_door_net_area
10.8108
11554.607069467089
FF_table_6b_roof_windows
0.7
11554.607069467089
FF_table_6b_roof_windows
0.693
11554.607069467089
external_wall_heat_capacity
190.0
11554.607069467089
external_wall_heat_capacity
191.9
11559.772638087601
area_north
8.99
11559.772638087601
area_north
8.9001
11564.006841277738
thermal_bridges_appendix_k
32.027
11564.006841277738
thermal_bridges_appendix_k
32.34727
11583.361999075458
hours_heating_is_off_1_weekend_living_room
0.0
11583.361999075458
hours_heating_is_off_1_weekend_living_room
0.0
11583.361999075458
pumps_and_fans_gains
[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
11583.361999075458
pumps_and_fans_gains
[2.97 2.97 2.97 2.97 2.97 2.97 2.97 2.97 2.97 2.97 2.97 2.97]
11583.514054510917
efficiency_of_water_heater
84.0
11583.514054510917
efficiency_of_water_

temperature_factor_table_2b
0.0
11891.91672493147
temperature_factor_table_2b
0.0
11891.91672493147
g_table_6b_south_east
0.68
11891.91672493147
g_table_6b_south_east
0.6868000000000001
11891.91672493147
solar_DHW_input_appendix_G
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
11891.91672493147
solar_DHW_input_appendix_G
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
11891.91672493147
efficiency_of_main_space_heating_system_1
84.0
11891.91672493147
efficiency_of_main_space_heating_system_1
84.84
11789.462606082525
semi_glazed_door_net_area
0.0
11789.462606082525
semi_glazed_door_net_area
0.0
11789.462606082525
hot_water_storage_loss_table_2
0.0
11789.462606082525
hot_water_storage_loss_table_2
0.0
11789.462606082525
mechanical_ventilation_air_change_rate_through_system
0.5
11789.462606082525
mechanical_ventilation_air_change_rate_through_system
0.505
11789.462606082525
assumed_occupancy
2.73
11789.462606082525
assumed_occupancy
2.7027
11790.430185755411
mechanical_ventilation_throughput_factor
0.0
11790.

solar_radiation_horizontal_plane_monthly_table_U3
[26, 54, 96, 150, 192, 200, 189, 157, 115, 66, 33, 21]
11629.60230499045
solar_radiation_horizontal_plane_monthly_table_U3
[ 26.26  54.54  96.96 151.5  193.92 202.   190.89 158.57 116.15  66.66
  33.33  21.21]
11618.043763958449
hours_heating_is_off_1_weekend_rest_of_dwelling
0.0
11618.043763958449
hours_heating_is_off_1_weekend_rest_of_dwelling
0.0
11618.043763958449
percentage_of_windows_and_doors_draught_proofed
100.0
11618.043763958449
percentage_of_windows_and_doors_draught_proofed
99.0
11623.13094271417
roof_opening
0.0
11623.13094271417
roof_opening
0.0
11623.13094271417
total_number_of_light_bulbs
10.0
11623.13094271417
total_number_of_light_bulbs
9.9
11621.414095361568
area
[0, 49.95, 48.99]
11621.414095361568
area
[ 0.     49.4505 48.5001]
11593.565839456322
ground_floor_net_area
49.95
11593.565839456322
ground_floor_net_area
49.450500000000005
11569.350991497746
ground_floor_u_value
0.76
11569.350991497746
ground_floor_u_valu

11859.333182229691
g_table_6b_roof_windows
0.68
11859.333182229691
g_table_6b_roof_windows
0.6868000000000001
11859.333182229691
window_u_value
1.8
11859.333182229691
window_u_value
1.818
11876.225048435945
efficiency_of_main_space_heating_system_2
0.0
11876.225048435945
efficiency_of_main_space_heating_system_2
0.0
11876.225048435945
basement_wall_gross_area
0.0
11876.225048435945
basement_wall_gross_area
0.0
11876.225048435945
g_table_6b_south
0.68
11876.225048435945
g_table_6b_south
0.6868000000000001
11869.60998545308


Plot results

In [39]:
SI

0            1  \
party_wall_net_area                                 0.000000     0.000000   
location_latitude_table_U4                       -976.653731  -976.653731   
g_table_6b_east                                     0.000000     0.000000   
air_permeability_value_q50                          0.000000     0.000000   
basement_wall_gross_area                            0.000000     0.000000   
...                                                      ...          ...   
hours_heating_is_off_2_weekday_rest_of_dwelling -1111.545102 -1111.545102   
pumps_and_fans_gains                               15.151609    15.151609   
solid_door_net_area                             -1197.601707 -1197.601707   
ground_floor_u_value                            -2281.330732 -2281.330732   
structural_infiltration                           631.927599   631.927599   

                                                           2            3  
party_wall_net_area                                 0.000000     0.000000  
location_latitude_table_U4                       -976.653731  -976.653731  
g_table_6b_east                                     0.000000     0.000000  
air_permeability_value_q50                          0.000000     0.000000  
basement_wall_gross_area                            0.000000     0.000000  
...                                                      ...          ...  
hours_heating_is_off_2_weekday_rest_of_dwelling -1111.545102 -1111.545102  
pumps_and_fans_gains                               15.151609    15.151609  
solid_door_net_area                             -1197.601707 -1197.601707  
ground_floor_u_value                            -2281.330732 -2281.330732  
structural_infiltration                           631.927599   631.927599  

[143 rows x 4 columns]

In [40]:
EE_table

{0: {'party_wall_net_area': 0.0,
  'location_latitude_table_U4': -976.6537305838938,
  'g_table_6b_east': 0.0,
  'air_permeability_value_q50': 0.0,
  'basement_wall_gross_area': 0.0,
  'g_table_6b_south': -661.5062982864401,
  'access_factor_table_6d_south': 623.6787142890535,
  'area_roof_windows': 0.0,
  'FF_table_6b_south': -639.7314470266792,
  'exposed_floor_net_area': 0.0,
  'g_table_6b_south_east': 0.0,
  'area_south_east': 0.0,
  'percentage_of_windows_and_doors_draught_proofed': 508.71787557207426,
  'assumed_occupancy': -68.64165152055648,
  'party_floor_heat_capacity': 0.0,
  'window_area': 29.945442888856633,
  'party_floor_net_area': 0.0,
  'external_wall_heat_capacity': 513.7076864213668,
  'mechanical_ventilation_air_change_rate_through_system': 0.0,
  'internal_floor_net_area': -24.958618736854987,
  'thermal_bridges_appendix_k': 2011.4374296001188,
  'access_factor_table_6d_north_west': 0.0,
  'internal_wall_net_area': 44.9701052491946,
  'area_east': 0.0,
  'roof_wind

In [41]:
energy

party_wall_net_area  location_latitude_table_U4  g_table_6b_east  \
run_1           11584.8633                11584.613714      11580.67989   
run_2           11584.8633                11574.847177      11580.67989   

       air_permeability_value_q50  basement_wall_gross_area  g_table_6b_south  \
run_1                11523.140405              11876.225048      11876.225048   
run_2                11523.140405              11876.225048      11869.609985   

       access_factor_table_6d_south  area_roof_windows  FF_table_6b_south  \
run_1                  11574.443103       11537.562575       11545.057242   
run_2                  11580.679890       11537.562575       11538.659927   

       exposed_floor_net_area  ...  g_table_6b_south_west  \
run_1            11538.659927  ...           11540.793372   
run_2            11538.659927  ...           11540.793372   

       internal_floor_heat_capacity  access_factor_table_6d_west  \
run_1                  11876.841544                 11522.135566   
run_2                  11877.093911                 11523.140405   

       access_factor_table_6d_south_east  \
run_1                       11579.255563   
run_2                       11579.255563   

       hours_heating_is_off_1_weekday_living_room  \
run_1                                11614.352205   
run_2                                11616.754067   

       hours_heating_is_off_2_weekday_rest_of_dwelling  pumps_and_fans_gains  \
run_1                                     11527.346827          11583.459429   
run_2                                     11516.231376          11583.610945   

       solid_door_net_area  ground_floor_u_value  structural_infiltration  
run_1         11589.930221          11569.350991             11583.610945  
run_2         11577.954204          11546.537684             11589.930221  

[2 rows x 143 columns]

In [42]:
total_energy_used=[v['total_energy_used'] for v in outputs.values()]
total_energy_used

[11876.225048435945, 11869.60998545308]

In [43]:
total_CO2_emissions_yearlys=[v['total_CO2_emissions_yearly'] for v in outputs.values()]
total_CO2_emissions_yearlys

[2554.00508912959, 2552.5762355252914]

In [44]:
output = pd.DataFrame(outputs)
output

run_1  \
volume                                              [0.0, 112.5987885, 110.4347277]   
total_floor_area                                                            97.9506   
dwelling_volume                                                             223.034   
number_of_chimneys_total                                                          0   
number_of_chimneys_m3_per_hour                                                    0   
...                                                                             ...   
energy_saving_generation_technologies_total_emi...                                0   
total_CO2_emissions_yearly                                                  2554.01   
dwelling_CO2_emission_rate                                                  26.0744   
CF                                                                          17.8663   
EI_rating                                                                   76.0591   

                                                                              run_2  
volume                                              [0.0, 112.5987885, 110.4347277]  
total_floor_area                                                            97.9506  
dwelling_volume                                                             223.034  
number_of_chimneys_total                                                          0  
number_of_chimneys_m3_per_hour                                                    0  
...                                                                             ...  
energy_saving_generation_technologies_total_emi...                                0  
total_CO2_emissions_yearly                                                  2552.58  
dwelling_CO2_emission_rate                                                  26.0598  
CF                                                                          17.8564  
EI_rating                                                                   76.0725  

[192 rows x 2 columns]

In [45]:
writer = pd.ExcelWriter('Morris_high.xlsx',engine = 'xlsxwriter')

In [46]:
energy.to_excel(writer,sheet_name = 'OAT')

In [47]:
writer.save()